import type { Metadata } from "next";
import "./globals.css";
import Footer from "../components/Footer/Footer";
import Navbar from "../components/Navbar/Navbar";
import ChakraProvider from "./providers/chakra-provider/chakra-provider";
import QueryClientProvider from "../../QueryClientProvider";
import { Box, Flex } from "@chakra-ui/react";
import { Toaster } from "@/components/ui/toaster";
import { LanguageProvider } from "./providers/language-provider/language-provider";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body>
        <QueryClientProvider>
          <ChakraProvider>
            <LanguageProvider>
              <Toaster />
              <Box h={["100dvh", "100vh"]}>
                <Flex flexDir="column" justify="center">
                  <Navbar />
                  <Box minH="100dvh">{children}</Box>
                </Flex>
                <Footer />
              </Box>
            </LanguageProvider>
          </ChakraProvider>
        </QueryClientProvider>
      </body>
    </html>
  );
}
